name: kahveci group research
title: kahveci group research
description: The Kahveci Group at Loyola University Chicago works at the interface of affective dimensions in chemistry education research. We apply quantitative research methods to analyze data and understand how learning complex chemistry topics is influenced by affective variables in relation to personal characteristics. Additionally, we are interested in studying dominant modalities of remote learning as an extension of the post pandemic influences on the practice of chemistry education.
url: 'https://kahveci.pw'
baseurl: ""
email: 'mkahveci@gmail.com'
timezone: America/Chicago

markdown: kramdown
permalink: /:title/
future: true
sass:
  sass_dir: css

input: GFM
math_engine: mathjax

analytics:
  provider: "google"
  google:
    tracking_id: "UA-129160204-1" # Replace with your actual Google Analytics tracking ID
  custom: true # This can be any value, its existence enables the custom script

plugins:
  - jekyll-twitter-plugin
  - jekyll-toc
  - jekyll-redirect-from

# Redirect configuration
jekyll_redirect_from:
  layout: "redirect"

defaults:
  # 1. Standard Jekyll Posts
  - scope:
      path: ""
      type: "posts"
    values:
      toc: true

  # 2. Seminars Collection (Assuming you want TOC here)
  - scope:
      path: ""
      type: "seminars"
    values:
      toc: true

  # 3. Projects Collection (Assuming you want TOC here)
  - scope:
      path: ""
      type: "projects"
    values:
      toc: true

  # 4. Misc Collection (TOC for those documents)
  - scope:
      path: ""
      type: "misc"
    values:
      toc: true
      layout: misc
      permalink: /:title/

collections:
  seminars:
    output: true
  projects:
    output: true
  misc:
    output: true
    date_field: null


toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

projects: []

readmes:
  - mkahveci/ai-in-education
  - mkahveci/qma
  - mkahveci/loyola-beamer-template


exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"




